### ISSUE TITLE
tang keys not being saved

### ISSUE THREAD

**Issue by FlexibleToast** [stackhpc/docker-tang#2]
When passing a volume to the container for /var/db/tang, nothing is being saved in that volume.

`podman run -d  -p 8080:80 -v /srv/tang:/var/db/tang --name tang ghcr.io/stackhpc/tang:latest`

Then if I check `/srv/tang` the `ls -al` returns nothing. The key generated won't be persistent when the container is upgraded.

**Comment by jovial** [comment]
Thanks for the report. Can confirm this issue with the docs not matching the directory configured in the [entry-point](https://github.com/stackhpc/docker-tang/blob/c49f5ab62b9cc90c7d9bb3ff0fdde98bfa07d355/root/usr/bin/tangd-entrypoint#L8), which is: `/var/cache/tang`. The [upstream default](https://github.com/latchset/tang/blob/b088c37a65a03c31223e64a5fcd47fb458244979/doc/tang.8.adoc) seems to be `/var/db/tang`. This would be a bit of a breaking change, but I think I'd prefer to change the entry-point to match the docs.

**Comment by jovial** [comment]
I've made a [v2.0.0](https://github.com/stackhpc/docker-tang/releases/tag/v2.0.0) release to make the database path match the documentation.
